image: docker.repo.usaa.com/usaa/java-ci:2.0.2

stages:
  - build
  - publish

test_and_build_artifact:
  stage: build
  script:
    - ./gradlew build sonarqube --stacktrace
  artifacts:
    paths:
      - build/reports/
    when: always
  tags:
    - docker

deploy_artifact:
  stage: publish
  script:
    - ./gradlew artifactoryPublish
  tags:
    - docker
  only:
    - master@grp-pi-gradle/sonarqube-quality-gates-plugin
    - tags

deploy_snapshot:
  stage: publish
  script:
    - ./gradlew artifactoryPublish
  tags:
    - docker
  except:
    - tags

pages:
  stage: publish
  script:
    - ./gradlew groovydoc
    - mkdir -p public/javadoc/
    - cp -R build/docs/groovydoc/* public/javadoc/
  artifacts:
    paths:
      - public/
  tags:
    - docker
  only:
    - tags 

